# Generated by Django 5.2.7 on 2025-10-21 17:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuarioperfil',
            name='sucursal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usuarios', to='core.sucursal'),
        ),
        migrations.AlterField(
            model_name='usuarioperfil',
            name='rol',
            field=models.CharField(choices=[('ADMIN', 'Administrador'), ('BODEGUERO', 'Bodeguero'), ('AUDITOR', 'Auditor'), ('PROVEEDOR', 'Proveedor')], default='ADMIN', max_length=20),
        ),
    ]
