# Generated by Django 5.2.6 on 2025-10-23 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_usuarioperfil_sucursal_alter_usuarioperfil_rol'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='precio',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=14, null=True),
        ),
        migrations.DeleteModel(
            name='PrecioProducto',
        ),
    ]
