# Generated by Django 5.2.6 on 2025-10-28 00:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_producto_ubicacion_stockubicacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockubicacion',
            name='ubicacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productos_stock_ubicacion', to='core.ubicacion'),
        ),
    ]
