# Generated by Django 4.2.1 on 2025-10-24 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_producto_precio_delete_precioproducto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imagenproducto',
            name='producto',
        ),
        migrations.AddField(
            model_name='producto',
            name='stock',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='AtributoProducto',
        ),
        migrations.DeleteModel(
            name='DefinicionAtributo',
        ),
        migrations.DeleteModel(
            name='ImagenProducto',
        ),
    ]
