# Generated by Django 5.2.6 on 2025-10-28 00:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_bodega_ubicacion'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='bodega',
            name='codigo',
        ),
    ]
