# Generated by Django 5.2.6 on 2025-10-28 01:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_bodega_codigo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sucursal',
            name='productos',
        ),
    ]
