# Generated by Django 5.2.6 on 2025-10-28 01:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_remove_sucursal_productos'),
    ]

    operations = [
        migrations.AddField(
            model_name='sucursal',
            name='productos',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='productos_sucursal', to='core.producto'),
        ),
    ]
