# Generated by Django 5.2.6 on 2025-10-28 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_sucursal_productos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sucursal',
            name='productos',
        ),
        migrations.AddField(
            model_name='sucursal',
            name='productos',
            field=models.ManyToManyField(blank=True, related_name='sucursales', to='core.producto'),
        ),
    ]
