# Generated by Django 5.2.6 on 2025-10-27 17:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_transferenciasucursal'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TransferenciaSucursal',
        ),
    ]
