# Generated by Django 5.2.6 on 2025-10-28 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_remove_sucursal_productos_sucursal_productos'),
    ]

    operations = [
        migrations.AddField(
            model_name='ubicacion',
            name='activo',
            field=models.BooleanField(default=True),
        ),
    ]
