# Generated by Django 5.2.6 on 2025-10-28 03:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_ubicacion_activo'),
    ]

    operations = [
        migrations.AddField(
            model_name='sucursal',
            name='ubicacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.ubicacion'),
        ),
    ]
